### ISSUE TITLE
REPL for rockstar

### ISSUE THREAD

**Issue by lanzhiheng** [RockstarLang/rockstar#119]
Does we have implement for rockstar language that we can try it in terminal directly like running in https://rockstar.connorwfitzgerald.com/

**Comment by gunnerwolf** [comment]
As far as I know, we don't have any fully functional implementations yet. Even rockstar-webpiler only parses the code to AST, and doesn't actually run it (yet)

**Comment by wrenoud** [comment]
I feel like this wouldn't be too hard to implement with [rockstar-py](https://github.com/yanorestes/rockstar-py) and [cmd](https://docs.python.org/3/library/cmd.html)...

**Comment by young-steveo** [comment]
I plan to have a REPL in [Thrash](https://github.com/young-steveo/thrash).

**Comment by marcinruszkiewicz** [comment]
I do actually have a working (though it's pretty barebones) REPL in [Kaiser-Ruby](https://github.com/marcinruszkiewicz/kaiser-ruby/tree/master), though I haven't finished implementing all of the language yet. But I'm planning to do that over the weekend.

```
$ kaiser-ruby rock --debug
Type 'exit' to exit the console. Otherwise, rock on!
\m/> Put "Hello San Francisco" into the message
\m/> the_message = "Hello San Francisco"
  => Hello San Francisco
\m/> Scream the message
\m/> puts the_message
Hello San Francisco
  => nil
\m/> exit
$
```

(TBH this looks much better in console than here, because the debug generated Ruby code is blue and stands out much more - also is togglable by that --debug flag there)

**Comment by cwfitzgerald** [comment]
The webpiler will be a little bit until it gets in browser code execution, in both REPL and program form so I would recommend to use one of the other impls if you need a REPL. My goal is to generate efficient code in Python/JS/C++/LLVM IR, and in order to do that I have to have a Static Single Assignment intermediate form to go to, and that requires quite a bit of work to create. Once I get proper SSA formed, I can start working on writing generators and runtimes, putting off type tracing and other optimization passes to later (as this is a desired feature.

**Comment by palfrey** [comment]
[Maiden](https://github.com/palfrey/maiden) is a fairly "complete" implementation (doesn't implement all the spec, but `cargo run <rockstar program>` works pretty well). At the moment the parser assumes it's only being handed complete programs, but [nom](https://docs.rs/nom/4.0.0/nom/) (which it's parser is written in) is pretty happy with parsing incomplete programs so you could probably build a REPL out of that. Not on my personal intended to-do list, but feel free to have a go :)

**Comment by AncientSwordRage** [comment]
I've asked for Rockstar to be added to tryitonline.net so I can use it in code golf puzzles on stackexchange

**Comment by AncientSwordRage** [comment]
Rockstar is now on tryitonline.net

Uncertain if its working
