### ISSUE TITLE
Proposal for Array syntax [WIP]

### ISSUE THREAD

**Issue by dylanrenwick** [RockstarLang/rockstar#121]
So I was thinking about this yesterday, and here's my proposal for array syntax:

## Definition:
Defining an array using the `contains` keyword:  
```
Array contains 123, 456
```
This would define `Array = [123, 456]`  
I thought about an empty array being an array with exactly 1 `null` and nothing else in it, although I'm not sure if that would cause problems (ie should there be a difference between `[]` and `[null]`)
```
Array contains nothing
```

### Appending:
```
Insert 789 into Array
```
This is to avoid ambiguity with `Put X into Y`, which is assignment

### Popping:
```
Take index from Array
```
This would define `first` as a keyword referencing the first index in the array, and `last` as a keyword referencing the last index in the array. Other than that, `index` should be a numerical value.  
This will *remove* the item at that position in the array (reindexing the array) and return it.  
I'm as yet undecided on how this value would then be referenced, because `Put take first from Array into Value` is horrible idiomatically and grammatically.

### Peeking:
```
index from Array
```
My idea was that `take` would basically be a special keyword to prefix a peek operation that would convert it to a pop operation. Peek will return the value at that index *without* removing it from the array.  
This works better idiomatically for putting into variables, as `Put first from Array into Value` reads better.

### Addition:
```
Bob contains 123, 456
Betty contains 654, 321

Put Bob plus Betty into Paul
```
This would concatenate the arrays, so that `Paul = [123, 456, 654, 321]`  

### Multiplication
```
Bob contains 123, 456
Put 3 into Betty

Put Bob times Betty into Paul
```
This would repeat the array, so that `Paul = [123, 456, 123, 456, 123, 456]`

### Subtraction
```
Bob contains 123, 456, 789
Put 456 into Betty

Put Bob minus Betty into Paul
```
This would remove the item from the array, so that `Paul = [123, 789]`

### Division
Array division doesn't make much sense.

## Length:
```
Bob contains 123, 456, 789

Put the length of Bob into Paul
```
This would of course return the length of Bob, so that `Paul = 3`  
This could also be used for string length possibly.

## Types
Given so much of the existing spec is based on ECMAScript, I would say Array types are arbitrary. IE  
```
Bob contains 123, "Hello", Cool Function, my heart
```
Would be valid, and would result in  
`Bob = [123, "Hello", function Cool Function(), <value of my heart>]`

Overall my main issue with this spec is the syntax for Popping, and if anybody has a better idea, please comment it!

**Comment by dancxjo** [comment]
"Contains" isn't a very common rock'n'roll word. Might I suggest "has"?

**Comment by gunnerwolf** [comment]
I'm concerned that may cause some ambiguity with the valid `'s\W+` syntax of poetic literals as, while that clause is supposed to allow contractions of is (Micheal's a cool guy), both examples given are contractions of has (Janie's got a gun). Of course `Janie has got a gun` wouldn't be valid syntax, even with `has` as an array assignment, because `got a gun` would be parsed as a single value, and is not a valid literal or variable name (Doesn't start with a valid common variable prefix, and isn't capitalized properly for a proper variable), but I'm still concerned about the possibly ambiguity here.

Curious to here what others think about it.

**Comment by cwfitzgerald** [comment]
As for the ambiguity. I think we would just have to make `has` non contactable which would be okay.

I agree with having arrays being arrays of anything, it makes things a little easier to do. Most of the syntax looks okay, though there is going to be a problem with taking the length of something. `Put the length of Bob into Paul` is already valid syntax because `of` is multiplication and `the length` is a valid identifier. https://rockstar.connorwfitzgerald.com/ooZFyzpltZ8 I think the core problem right now is that we need a way to deal with calling methods on objects. If we have a way to do this, there will be a single shared syntax which would make introducing these features much easier to deal with. We can worry about adding additional sugar on top of them later. I don't know what that would be at the moment, mostly because I'm tired and didn't sleep enough :)

**Comment by gunnerwolf** [comment]
I agree. Fundamentally we need object definition and access syntax to be able to properly define things like the length of an array.

**Comment by dylanrenwick** [comment]
Or we could do it python style and have a language-level keyword function that returns the length of its argument

**Comment by gaborsch** [comment]
I'd propose `at` for indexing.

`Put your hands at Midnight into my hands` (my hands := your hands[Midnight] )
`Put my hands at Midnight into your hands (your heart[Midnight] := my hands) `

For stack operations, I'd propose `Push .. into ... (push)`, `Pull ... from ... (pop)` and `Last of ... (peek)` 
`Push your last coin into the machine`
`Pull the trigger from your will`
`If the last of the zombies is gone`

For count/lenght/sizeof operation, I recommend `count of`:
`If count of your dreams is nothing`

Emptiness check can be performed by `Null` type to be casted to empty array, regarding array context:
`While your dreams is empty`
