### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by rmd6502** [RockstarLang/rockstar#124]
This is more of a concept than an actual proposal, but something on the order of:

breaks, turns, goes would be equivalents to catch, and the try block would be given a name, allowing clearly delineated nested blocks.
`my heart is in your hands`
...
`If my heart breaks` - terminates block named 'my heart'
`If my world turns to ash` - terminates block named 'my world' and saves the exception object in variable 'ash' - or would it be better to just store the exception in 'my world'?
Perhaps the exception could be rethrown with throw, raise, bring, take, or send, e.g.
`bring my world higher`
`take it higher`, where using it would be the equivalent of anonymous raise.

Instead of If, using 'when' might be better and less ambiguous

**Comment by cwfitzgerald** [comment]
You're going to have to expand on this a little more. `my heart is in your hands` is [already a valid expression](https://rockstar.connorwfitzgerald.com/78xvqAn5A3k), so it would leave this extremely ambiguous. Especially because of the changes in #117, reserved words, as `in` would have to be, are not given special treatment at the beginning of a poetic literal. I would advise that we have completely different syntax for handing exceptions. We do not want to 'overload' the syntax we already have too much.

**Comment by rmd6502** [comment]
ah, okay - the spec is changing faster than I'm reading it - I'll revisit and elaborate

**Comment by rmd6502** [comment]
Perhaps `my heart may break` instead
