### ISSUE TITLE
Should Poetic Literal Assignment allow expressions other than individual Literal Words?

### ISSUE THREAD

**Issue by young-steveo** [RockstarLang/rockstar#129]
This question is related to https://github.com/dylanbeattie/rockstar/pull/128, https://github.com/dylanbeattie/rockstar/pull/127, and https://github.com/dylanbeattie/rockstar/issues/112.

Should we allow poetic literal assignment to contain expressions other than the literal words themselves (e.g. arithmetic).

In other words, should:

```
Tommy is nothing plus love
```

be a syntax error, or should it be equivalent to `Tommy = 0 + love`.

**Comment by gunnerwolf** [comment]
In my opinion it introduces ambiguity.

Sure in this case the choice is between  0 + love or error, but what if it's `Tommy is workout plus love`, is that `Tommy = 7 + 4` or `Tommy = 74`?

With that in mind personally I think it should be a syntax error.

**Comment by young-steveo** [comment]
I think `Tommy is workout plus love` is clearly `744` since `workout` is not a literal word.

**Comment by yanorestes** [comment]
I'm not sure how ambiguous is that, actually. `Tommy is workout plus love` should mean `Tommy = 744`, and that's it, because any keyword that appears inside (not as the first word of) the poetic literal is treated as part of the poetic literal. `Tommy is nothing plus love` shouldn't work, because `love` is not a valid variable name. However, `Tommy is nothing plus my love` should translate to `Tommy = 0 + my love`

**Comment by young-steveo** [comment]
My take on it:  Standard assignment right now is pretty boring.  Every rockstar app is full of:

```
Put my heart into your hands
Put love into the world
Put x into y
```

So giving the rockstar programmer another lyrical outlet would be a boon.

**Comment by marcinruszkiewicz** [comment]
My take in #128 was this:

`Tommy is nothing plus my love` -> syntax error
`Tommy is nothing` -> `Tommy = 0`
`Tommy thinks nothing plus my love` -> `Tommy = 0 + my love` 

With a different keyword to keep it distinct. Because if we keep adding things to `is` the next issue is gonna be "can I assign a variable to a variable this way and why not", and `is` is already used in conditionals as well.

Because @young-steveo is right and without something we can only do `Put nothing plus my love into Tommy`, which isn't as cool as a poetic version.

**Comment by cwfitzgerald** [comment]
I am inclined to follow @marcinruszkiewicz's plan, adding another keyword will simultaneously allow parsers to be easier to design and remove ambiguity in the language. I think we should aim to reduce ambiguity as much as we can, without losing the poetic power of the language, and I think this is a good way of doing this. 
---
Connor Fitzgerald

**Comment by zzucco** [comment]
I worry that no keyword offers the flexibility of `is` for standard assignment. What we need is a clear way to differentiate when `is` refers to poetic assignment and when it doesn't.

My suggestion is that any `is` followed by a variable or a literal keyword be treated as an expression, not a poetic assignment.
`Force is Meaningless without Skill` -> Force = Meaningless - Skill
`Force is meaningless without skill` -> Force = 175
`A Craftsman is nothing without His Tools` -> A Craftsman = 0 - His Tools

This does increase the ambiguity of `is` but I think that it's worth it.

**Comment by cwfitzgerald** [comment]
While I do see what you're saying, I think we should have two distinct syntaxes (syntaxi? syntaxum?) as it solves both problems, expressiveness in the language and ambiguity in writing things. I don't think we should leave it at only `thinks`, we can add other aliases as we please, but it is a good start.

**Comment by dylanbeattie** [comment]
There's active discussion going on over on the Discord channel about this, but I think we need to support one keyword that takes a constant or poetic literal on the RHS, and a separate keyword (`thinks` works for now) that supports an expression on the RHS.
