### ISSUE TITLE
Equality and truthiness with strings

### ISSUE THREAD

**Issue by palfrey** [RockstarLang/rockstar#168]
* According to [truthinessTest](https://github.com/dylanbeattie/rockstar/blob/reference-implementation/tests/correct/truthinessTest.rock), `if "hello"` says `"hello"` is truthy
* According to [equalityComparison](https://github.com/dylanbeattie/rockstar/blob/reference-implementation/tests/correct/operators/equalityComparison.rock) `say true is "hello"` says `"hello"` is falsey

Which one is it? Binary comparison says "Convert the string to a boolean using all defined aliases" but then doesn't define what to do in the failure case, and Truthiness says "String - Truthy" (with no qualifiers).

**Comment by wizered67** [comment]
These behaviors aren't necessarily exclusive. In Python for example, `if "hello": print("hello")` will print "hello", but `print("hello" == True)` prints False. That being said, we should clearly define the intended behavior when the string can't be converted to a boolean. 

I'm actually wondering if converting the string "false" to the boolean false when comparing them is confusing. In `if "false"` and `if "false" is true` would have different behavior since the comparison converts it but the conditional treats all non-empty strings as truthy. 
 `

**Comment by palfrey** [comment]
There's a related issue in `nothing.rock` in that the empty string is defined as equal to null, despite the spec saying `String <op> Null => Non equal.`
