### ISSUE TITLE
Undeclared variables

### ISSUE THREAD

**Issue by ascheja** [RockstarLang/rockstar#199]
Currently, an undeclared variable creates an error in satriani when referenced, but according to the spec it should rather be treated as `mysterious`.

**Comment by dylanbeattie** [comment]
OK, this is another one of those 'seemed like a good idea when it was just a parody spec' things.

I nicked the idea of `mysterious` from JavaScript, where you can explicitly declare a variable without assigning it a value. 

```
var x; // x is now undefined, and (x == undefined) is true
```

But in JavaScript, if you just go

```
console.log(no_such_variable);
```

you don't get 'undefined', you get `Uncaught ReferenceError: no_such_variable is not defined`

In Rockstar, there's actually no way to declare a variable without initialising it... so having an uninitialised variable equal `mysterious` means if you make typos in your variable names it'll silently ignore them, the typos will be `mysterious` and it'll fail at runtime.

Options are:

1. Remove `mysterious` completely. `null` and its aliases actually cover almost every edge case that'll come up in valid Rockstar programs
2. Modify Satriani so that any undeclared variable will just be `mysterious` - this gives you a bit more freedom to include (unused) variables in your Rockstar programs to make them more poetic, but I don't really like it.
3. Add the idea of explicit variable declaration decoupled from assignment, a la JavaScript.

Thoughts?

**Comment by ascheja** [comment]
I'm not a fan of the ecmascript type system anyway, so I'd be in favor of option 1. But it would be nice if we could define how to handle things like missing return from a function or not enough arguments being passed to a function in the spec (both cases currently result in `mysterious` in my implementation, and I think at least for the missing return the behavior in satriani is the same)

**Comment by hugobuddel** [comment]
Rocky behaves like option 2, which indeed led to several 'mysterious' bugs due to typo's.

However, it also saves a line of lyrics when variables are only declared in `If`-blocks. E.g. this song
```
The night was dark

Fall is coming
If the night is fall
Our king is slain

While our king is not slain
Shout "in agony"
```
requires an extra line in Satriani to set our king, either before the `If` statement or in an `Else` block. Not so bad, but the more lines are forced, the less poetic the lyrics become.

Related, I don't know how to actually get a `null` value. I got one before, but don't recall how.

**Comment by hugobuddel** [comment]
Maybe I should use more pronouns, because it seems they can be used for a similar effect. E.g.
```
The night was dark
Listen to the day

If the night is the day
Our king was slain by a dragon

Say it
```
where the value of `it` will only be the value of `our king` if the `If` block executed.
