### ISSUE TITLE
Case-sensitivity in common variables

### ISSUE THREAD

**Issue by palfrey** [RockstarLang/rockstar#212]
So, there appears to be some contradictions in the spec and the current test suite, and I'm trying to resolve them.

First, the spec "Common variables consist of one of the keywords a, an, the, my or your followed by whitespace and a unique variable name, which must contain only lowercase ASCII letters a-z. The keyword is part of the variable name, so a boy is a different variable from the boy. Common variables are case-insensitive." - this seems to contradict itself, in that the unique variable name "must contain only lowercase ASCII" but "Common variables are case-insensitive". I'm not sure what the intent is here?

Then the test at https://github.com/RockstarLang/rockstar/blob/master/tests/fixtures/variables/proper_variables.rock which has the line "MY HEART IS "BROKEN" I'm wondering now, is "MY HEART" meant to be a proper variable (given the test name), despite starting with "MY", which would normally indicate a common variable... If so, there should probably be a comment noting this being an unusual case.

**Comment by palfrey** [comment]
Also seeing related issues in https://github.com/RockstarLang/rockstar/blob/master/tests/fixtures/variables/simple_variables.rock - "Variable is 1" is fine, but "Say variable" I would have assumed needed uppercase Variable, and the same for the other names in that file.

**Comment by gaborsch** [comment]
I think that there's no big difference between the different variable types. Variables are variables, and there are 3 different flavors how you can name and use them, but it's all the same in the background.

Actually all variable types are case insensitive. If you declare a variable as `MY HEART` (as a proper variable), you can access it as `my heart` common variable name, it's going to be the same variable. That's why those examples are working.

If you think on a plain English text, you capitalize all line starter characters, regardless they are proper names or simple nouns. If we didn't have the above rule, we should have used the capitalized variable name (as a proper variable name) in all later occurrences, which would lead a weirdly cased lyrics. The intention was to avoid cases like this:
```
My destiny was over
Darkness was going to come
Let my hour be **D**arkness over **M**y destiny
```

**Comment by palfrey** [comment]
The problem is now in order to be able to write an interpreter, if I see one or more words that aren't otherwise significant, I need to assume they're a variable and then figure out at runtime if they are or not, even if they violate the rules.

"variable" is a good example - it's not a valid proper variable as it's doesn't start with a capital letter and it's not a common variable as it doesn't start with a/an/the/my/your, but according to the test I'm meant to regard it as a variable despite that.

**Comment by gaborsch** [comment]
"variable" is a Simple variable in this case.

I think that you should not assume that something you cannot interpret is a variable name, rather you shoud check whether either of the 3 rules (Simple, Proper, Common) can be applied, If yes, it's a variable name, if not, it's syntax error.

**Comment by palfrey** [comment]
Ah! I'd managed to completely fail to miss the simple variables. Think they got added since the last time I read the spec fully. Thanks!
