### ISSUE TITLE
Satriani breaks on nested parentheses

### ISSUE THREAD

**Issue by Superbird11** [RockstarLang/rockstar#237]
Satriani (or, at least, the deployment at https://codewithrockstar.com/online) produces an error when parentheses are used within a comment (that is, inside parentheses). 

Specifically, it's right-paren that seems to be causing the issue, as it's the character that closes the comment. This causes an error, as it probably should:

```
())
```

However, the following input also produces an error:

```
(())
```

which is restrictive. If, say, I was writing a function in Rockstar and wanted to notate what it would be doing in pseudocode, I would want to do something like this:

```
Modulo takes divisor and dividend                  ( func Modulo(divisor, dividend)         )
  Let quotient be divisor over dividend            (   quotient = divisor / dividend        )
  Turn down quotient                               (   quotient = floor(quotient)           )
  Give back divisor minus quotient times dividend  (   return divisor - quotient * dividend ) 
```

then it doesn't compile, because `Modulo(divisor, dividend)` breaks the comment. So does `floor(quotient)`.

**Comment by dylanbeattie** [comment]
This behaviour is by design. Think about how, e.g. block comment syntax works in C-style languages:

![image](https://user-images.githubusercontent.com/106178/75562093-f484ba00-5a3f-11ea-9dd6-8cfbd75d861d.png)

The language grammar defines a comment as a `(`, followed by any number of non-`)` characters, followed by a `)`, which makes parsing comments fast and state-free (and hence very simple to implement.)

There might be an argument for an alternative comment syntax, so you can nest one comment syntax inside the other, but I don't know of any language that supports multiple levels of nesting in block comment syntax... and I know Rockstar is unconventional by design, but that's just too weird.
