### ISSUE TITLE
Aliases for takes/taking

### ISSUE THREAD

**Issue by jerryjeremiah** [RockstarLang/rockstar#247]
I find takes/taking just a bit inflexible.
Most other parts of the language have aliases but takes/taking don’t seem to have any.. 
I was thinking that takes could also be uses, requires, accepts and receives
And then taking could also be using, passing, and sending
Then you could talk about "using a guitar", “passing the buck“, "sending smoke signals", "requires lots of patience", “accepts a bribe”, or “receives a gift”

What do you think?

**Comment by hapaxlego** [comment]
I noticed there are a lot of open issues proposing aliases, some of them for takes/taking too. I considered scrolling throu them and summarizing them in a unique issue with links to the original discussion, since it would sometimes make sense to consider them toghether or to discuss some general criteria. I am not sure if this would make things clearer or just add confusion, so I will wait for other opinions.
I also noticed a lot of exemple proposal in the issues without a pull request. I will probably deal with mine, but since I would scroll the issues anyway I could at least give a hint to others to do the same thing. What do you think?

**Comment by jerryjeremiah** [comment]
I have already made changes to my copy of the language for things I saw mentioned that I thought were good ideas.  I don't mind if changes are made to everybody else's version or not and I won't be the first person to make local changes and not have those changes incorporated more widely.  I didn't realise that sharing would get a negative response - forget I mentioned it.

If I find time I might summarise all the open issues into one so that no one has to scroll through them.  It would be good to have a summary.  I'll update this one with that info if I ever get to it.
