### ISSUE TITLE
One closing parenthesis closes all parenthesis

### ISSUE THREAD

**Issue by thebees86** [RockstarLang/rockstar#340]
```
(This is a comment)
(This is a (nested comment))
```
One would assume that the above are both valid comments, but Satriani closes all parenthesis when it encounters one closing parenthesis, so the second comment is marked as invalid. While comments are discouraged in Rockstar, this behavior is not mentioned in the docs, and goes against the standard behavior of nested parenthesis.

A few examples from testing this on the official website are attached below.

![image](https://github.com/user-attachments/assets/6755bdf2-2898-40c2-ba8b-f8fe81362cee)
![image](https://github.com/user-attachments/assets/f16c33cc-fb66-41c4-bccb-4ad048017516)

**Comment by dylanbeattie** [comment]
You're right that this is not covered in the spec... I'll see if we can support nested parentheses in Rockstar 2, otherwise I'll update the docs to make it clear this isn't supported. (It requires stateful parsing which means maintaining a stack inside the parser to see how many comments deep you are, which isn't something that any other Rockstar feature currently requires, but I don't think it's *that* hard to implement.)

**Comment by dylanbeattie** [comment]
Rockstar now supports nested comments:

https://codewithrockstar.com/docs/01-getting-started.html#comments
