### ISSUE TITLE
"For every" loop has issues with array elements inserted during the loop

### ISSUE THREAD

**Issue by caseyc37** [RockstarLang/rockstar#353]
Test code:

```My flaw is eternal purple
My words are silent
Rock my flaw into my words
Rock my flaw into my words
Rock my flaw into my words
Rock my flaw into my words
Rock my flaw into my words
Rock my flaw into my words
Rock my flaw into my words
Rock my flaw into my words
Rock my flaw into my words

My answer is pure truth
The first is purple green
Rock my answer
Roll my answer
Shatter my words
For every letter in my words
  Burn the first into reality
  Let my answer at reality be so vital
  Build the first up
  Shout my answer

Scream my answer
```

What the code does: It creates an array and then goes through it with "For every letter in my words". Inside that loop it writes hashes to an unrelated array.

On exiting the loop, the unrelated array is abruptly empty.

**Comment by dylanbeattie** [comment]
Fixed in https://github.com/RockstarLang/rockstar/commit/9946a693efd5b3c8d668beeee0be2d51b9bafc46 - for-in and for-of loops were extending scope to capture the loop variables, which meant anything declared or assigned inside the loop body would be discarded when exiting the loop. This was clearly not how loops are supposed to work... :)
