### ISSUE TITLE
"a" is really "A" evaluates to true

### ISSUE THREAD

**Issue by mikachelya** [RockstarLang/rockstar#355]
capital letters are incorrectly exactly equal to lowercase ones.
`print "a" is really "A"` prints `true`. Currently you have to cast both into numbers to avoid this.
I'd argue that `"a" is "A"` should be false, let alone when using strict equality.

![Screenshot 2024-12-08 234838](https://github.com/user-attachments/assets/255dffb9-d849-40b1-a864-9f2ca2dff2f5)

**Comment by dylanbeattie** [comment]
Fixed in https://github.com/RockstarLang/rockstar/releases/tag/v2.0.12

String comparison (equality and identity) is now case sensitive.

I've also overloaded the `turn up` and `turn down` functions to convert strings to UPPERCASE/lowercase, so if you need to do a case-insensitive string comparison you can convert the strings to upper/lower case before comparing them.

`turn around` reverses a string now. Because that's what it sounds like it should do.
