### ISSUE TITLE
Pronouns as array indexes cause segfault

### ISSUE THREAD

**Issue by MeWhenI** [RockstarLang/rockstar#368]
Using a pronoun as an index to update an array can sometimes cause a segfault, thought it does not seem to cause that the first time it is done.
```
for x in 3
n=0
r at i=0
```
This code segfaults, but has no issue if the `3` is changed to a smaller number

**Comment by dylanbeattie** [comment]
This was a really interesting one to figure out 😀

```
for x in 3
n = 0
array at it = 0
```

First time through, 'array' is undefined at the point we assign 'it' -  so we assign `array[mysterious] = 0`. Second time through, `array` exists,  so `array at it = 0` assigns `array[array] = 0` - and updates `it` to point to `array[array]` but **does not actually evaluate it**

But once you've got an array that uses itself as an index, any attempt to assign, read, write, debug, etc. that array causes an infinite loop. 

The fix modifies the code so that the pronoun subject is only updated AFTER the assignment operation has completed, so any pronouns used in array index expressions will retain the values they had when the assignment started and won't change value halfway through.
