### ISSUE TITLE
Odd behaviour when copying values in recursive function

### ISSUE THREAD

**Issue by caseyc37** [RockstarLang/rockstar#369]
Consider these two programs:

```
Your hope is everything
Denial is unhelpful

Polly wants a cracker
  Until a cracker is denial
    Build a cracker up
    My food is now a cracker
    Polly taking a cracker
    A cracker is now my food
    Scream a cracker



Polly taking your hope
```

and

```
Your hope is everything
Denial is unhelpful

Polly wants a cracker
  Until a cracker is denial
    Build a cracker up
    Let my food be a cracker
    Polly taking a cracker
    Let a cracker be my food
    Scream a cracker



Polly taking your hope
```

The only difference is how they assign variables in the recursive function - note that the same variables are assigned to the same place, only the syntax is different.

These produce different outputs. I'm pretty sure that's wrong.

**Comment by dylanbeattie** [comment]
This might appear confusing, but it's by design. `Let X be Y` and `X is now Y` are not actually interchangeable; `let` will always declare a new variable in the current scope -- i.e. the function body, because Rockstar uses function scoping similar to JavaScript --  whereas `is` will overwrite/update a global variable if one exists, and will only declare a new variable in local scope if it doesn't find any variable matching that name in any parent scope.

https://codewithrockstar.com/docs/08-functions.html#variables-closures-and-function-scope
