### ISSUE TITLE
Other Data Types

### ISSUE THREAD

**Issue by N-Masi** [RockstarLang/rockstar#38]
I know this is a relatively basic language but I feel like you could make it more legitimate and allow for more complex programs with the inclusion of more complex data types such as an array. 

Syntax could work where ```filled with``` denotes the start of what to fill the array with and you separate the items with ```but```, ```and```, or ```or```. The value of the first data entry that isn't ```null``` or an alias of it would determine what data type the array is.

```
a shout was loud
a scream was quiet
the nights filled with nothing but a shout and a scream
```
would fill the array ```the nights``` with ```null``` at 0, ```4``` at 1, and ```5``` at 2. Because ```a shout``` is a number it makes ```the nights``` an array containing number types, meaning accessing position 0 would return 0 because that is the number equivalent of ```null```.

You could also chose not to fill the array at it's initialization which would require stating how large it needs to be which could be done using poetic number literals that are preceded by the phrase ```full of```. The data type which is contained by the array would remain ```mysterious``` until a non-```null``` value was input into it.

```the nights full of darkness```
would create the array ```the nights``` of type ```mysterious``` having 8 spots.

To reference a specific position in the array, to either get the value stored there or assign it a new value, you would state the array name, then the reserved word ```at```, followed by a poetic number literal, and then either ```is``` to assign or ```into``` to retrieve. To access the zeroth position you would have ```null``` or any of its aliases following ```at```, this must be done because you obviously can't use a word of no length.

```the man at dawn is "weary"```
would fill the 4th position in ```the man``` with the string literal ```"weary"```.

```put the man at rest into a casket```
would take the value in the 4th position of ```the man``` and assign it to the variable ```a casket```.

**Comment by crusaderky** [comment]
The problem with both this and #54 is that you can't perform an indirect access to the array, and you must know the size of it at the moment of writing the program. This makes it effectively have zero benefit compared to a bunch of named scalar variables.

For example, with the current rockstar as well as with either of these proposals, it's impossible to write a program such as "read lines from stdin until you get" stop", then print them out in reverse order ". This i suspect makes rockstar not Turing complete by the way. It is otherwise a  simple problem in any Turing language with a turning cilinder eg brainfuck.

**Comment by cwfitzgerald** [comment]
There's another issue with this syntax that would make parsing hard. Poetic number literals have the freedom to use any word, even reserved words. If we want something like `the man at dawn is "weary"` there needs to be a restriction on the words that poetic number literals can contain. I've checked both my parser and @yanorestes's parser and we both scan for poetic number literals the same way, using a "give me everything" glob. While we could add checks for every single possible keyword for that particular case, it would make parsing of number literals difficult. 

I would also be very interested in hearing from other implementers how they did it and what they thing of this problem.

**Comment by yanorestes** [comment]
> To access the zeroth position you would have null or any of its aliases following at, this must be done because you obviously can't use a word of no length.

You can just use a word with length 10, because it is always module 10. 

@cwfitzgerald we'd need to check for array access before poetic number literal assignments

**Comment by cwfitzgerald** [comment]
@yanorestes I have a full recursive decent parser, so that's not really a problem, but it would still mean we will have to have two different implementations of poetic number literals. Additionally it would be annoying to have users of the language have to deal with "poetic number literals behave this one well defined way...except this one edge case where it does weird things"

**Comment by N-Masi** [comment]
Oh yeah I forgot about the modulus 10 thanks @yanorestes

**Comment by yanorestes** [comment]
@cwfitzgerald agreed!

**Comment by young-steveo** [comment]
Somehow nesting poetic numbers into an expression, followed by non-poetic keywords would be really hard to lex and parse.
